version: "3.7"

services:
  # image project
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./chamados-app/:/var/www
    depends_on:
      - mysql
    networks:
      - laravel

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./chamados-app:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  # db mysql
  # db:
  #     image: mysql:5.7.22
  #     platform: linux/x86_64
  #     restart: unless-stopped
  #     environment:
  #         MYSQL_DATABASE: ${DB_DATABASE:-laravel}
  #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
  #         MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
  #         MYSQL_USER: ${DB_USERNAME:-username}
  #     volumes:
  #         - ./.docker/mysql/dbdata:/var/lib/mysql
  #     ports:
  #         - "3388:3306"
  #     networks:
  #         - laravel

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=orders
      - MYSQL_ROOT_PASSWORD=secretpsw
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql-volume:
    driver: local

networks:
  laravel:
    driver: bridge
